const vocables = (german, norsk) => [
  // Voc. Lection 1
  { [german]: ['arbeiten'], [norsk]: ['arbeide'] },
  { [german]: ['alle'], [norsk]: ['alle'] },
  { [german]: ['alle zusammen'], [norsk]: ['alle sammen'] },
  { [german]: ['ein Au-pair', 'eine Au-pair', 'eine Au Pair'], [norsk]: ['en au pair'] },
  { [german]: ['nur'], [norsk]: ['bare'] },
  { [german]: ['ein Tag'], [norsk]: ['en dag'] },
  { [german]: ['sie'], [norsk]: ['de', 'hun'] },
  { [german]: ['dort'], [norsk]: ['der'] },
  { [german]: ['ihr'], [norsk]: ['dere'] },
  { [german]: ['das', 'es'], [norsk]: ['det'] },
  { [german]: ['dies'], [norsk]: ['dette'] },
  { [german]: ['du'], [norsk]: ['du'] },
  { [german]: ['ein Elch'], [norsk]: ['en elg'] },
  { [german]: ['englisch'], [norsk]: ['engelsk'] },
  { [german]: ['bin', 'bist', 'ist', 'sind', 'seid'], [norsk]: ['er'] },
  { [german]: ['ein Urlaub'], [norsk]: ['en ferie'] },
  { [german]: ['im Urlaub sein'], [norsk]: ['være på ferie'] },
  { [german]: ['aus', 'von'], [norsk]: ['fra'] },
  { [german]: ['Frankreich'], [norsk]: ['Frankrike'] },
  { [german]: ['französisch'], [norsk]: ['fransk'] },
  { [german]: ['gern'], [norsk]: ['gjerne'] },
  { [german]: ['machen', 'tun'], [norsk]: ['gjøre'] },
  { [german]: ['gut'], [norsk]: ['god'] },
  { [german]: ['haben'], [norsk]: ['ha'] },
  { [german]: ['er'], [norsk]: ['han'] },
  { [german]: ['hallo', 'hey', 'hei'], [norsk]: ['hei'] },
  { [german]: ['hier'], [norsk]: ['her'] },
  { [german]: ['heißen'], [norsk]: ['hete'] },
  { [german]: ['was', 'wie'], [norsk]: ['hva'] },
  { [german]: ['wer'], [norsk]: ['hvem'] },
  { [german]: ['wo'], [norsk]: ['hvor'] },
  { [german]: ['pst!', 'Ruhe!'], [norsk]: ['hysj!'] },
  { [german]: ['in'], [norsk]: ['i'] },
  { [german]: ['Italien'], [norsk]: ['Italia'] },
  { [german]: ['italienisch'], [norsk]: ['italiensk'] },
  { [german]: ['ja'], [norsk]: ['ja'] },
  { [german]: ['ich'], [norsk]: ['jeg'] },
  { [german]: ['kann', 'kannst', 'können', 'könnt'], [norsk]: ['kan'] },
  { [german]: ['kommen'], [norsk]: ['komme'] },
  { [german]: ['können'], [norsk]: ['kunne'] },
  { [german]: ['frei'], [norsk]: ['ledig'] },
  { [german]: ['lernen'], [norsk]: ['lære'] },
  { [german]: ['ein Lehrer', 'eine Lehrerin'], [norsk]: ['en lærer'] },
  { [german]: ['ein bisschen', 'bisschen', 'wenig'], [norsk]: ['litt'] },
  { [german]: ['man'], [norsk]: ['man'] },
  { [german]: ['mehr'], [norsk]: ['mer'] },
  { [german]: ['nein'], [norsk]: ['nei'] },
  { [german]: ['Norwegen'], [norsk]: ['Norge'] },
  { [german]: ['norwegisch'], [norsk]: ['norsk'] },
  { [german]: ['und'], [norsk]: ['og'] },
  { [german]: ['auch'], [norsk]: ['også'] },
  { [german]: ['auf', 'in'], [norsk]: ['på'] },
  { [german]: ['zusammen'], [norsk]: ['sammen'] },
  { [german]: ['sitzen'], [norsk]: ['sitte'] },
  { [german]: ['sprechen'], [norsk]: ['snakke'] },
  { [german]: ['ein Sprachkurs'], [norsk]: ['et språkkurs'] },
  { [german]: ['im Sprachkurs'], [norsk]: ['på språkkurs'] },
  { [german]: ['ein Student', 'eine Studentin'], [norsk]: ['en student'] },
  { [german]: ['studieren'], [norsk]: ['studere'] },
  { [german]: ['die Schweiz', 'Schweiz'], [norsk]: ['Sveits'] },
  { [german]: ['schweizerisch'], [norsk]: ['sveitsisk'] },
  { [german]: ['zu', 'nach', 'in', 'bis'], [norsk]: ['til'] },
  { [german]: ['deutsch'], [norsk]: ['tysk'] },
  { [german]: ['Deutschland'], [norsk]: ['Tyskland'] },
  { [german]: ['willkommen in'], [norsk]: ['velkommen til'] },
  { [german]: ['wir'], [norsk]: ['vi'] },
  { [german]: ['will', 'willst', 'wollen', 'wollt'], [norsk]: ['vil'] },
  { [german]: ['wollen'], [norsk]: ['ville'] },
  { [german]: ['sein'], [norsk]: ['være'] },
  { [german]: ['zu (vor Infinitiv)', 'zu'], [norsk]: ['å'] },
  { [german]: ['entspannen'], [norsk]: ['slappe av', 'avspenne'] },

  // From here sentences to practise (Lection 1)
  { [german]: ['Wie heißt du?', 'Wie heißen Sie?'], [norsk]: ['Hva heter du?'] },
  { [german]: ['Ich heiße Thomas.'], [norsk]: ['Jeg heter Thomas.'] },
  { [german]: ['Ich bin aus Deutschland.', 'Ich komme aus Deutschland.'], [norsk]: ['Jeg er fra Tyskland.', 'Jeg kommer fra Tyskland'] },
  { [german]: ['Woher kommst du?'], [norsk]: ['Hvor kommer du fra?'] },
  { [german]: ['Was machst du in Norwegen?'], [norsk]: ['Hva gjør du i Norge?'] },
  { [german]: ['Ich studiere. Ich bin Student.'], [norsk]: ['Jeg studerer. Jeg er student.'] },
  { [german]: ['Ich arbeite. Ich bin Lehrer.'], [norsk]: ['Jeg arbeider. Jeg er lærer.'] },
  { [german]: ['Ich mache Urlaub hier.'], [norsk]: ['Jeg er på ferie her.'] },
  { [german]: ['Spricht Anna italienisch?'], [norsk]: ['Snakker Anna italiensk?'] },
  { [german]: ['Wer sitzt dort?'], [norsk]: ['Hvem sitter der?'] },
  { [german]: ['Ich möchte gerne in Norwegen studieren.'], [norsk]: ['Jeg vil gjerne studere i Norge.'] },
  { [german]: ['Möchtet ihr auch spanisch lernen?'], [norsk]: ['Vil dere også lære spansk?'] },
  { [german]: ['Wo können wir sitzen?'], [norsk]: ['Hvor kan vi sitte?'] },
  { [german]: ['Wo seid ihr im Urlaub?'], [norsk]: ['Hvor er dere på ferie?'] },
  { [german]: ['Woher kommst du?'], [norsk]: ['Hvor er du fra?', 'Hvor kommer du fra?'] },
  { [german]: ['Wie geht es dir?'], [norsk]: ['Hvordan har du det?', 'Hvordan går det?'] },
  { [german]: ['Danke, mir geht es gut.', 'Danke, ganz gut.'], [norsk]: ['Takk, ganske bra.'] },

  // Voc. Lection 2
  { [german]: ['bedeuten'], [norsk]: ['bety'] },
  { [german]: ['eine Sahnetorte'], [norsk]: ['ei bløtkake'] },
  { [german]: ['ein Tisch'], [norsk]: [''et bord] },
  { [german]: ['gut'], [norsk]: ['bra'] },
  { [german]: ['ein Brauch', 'eine Nutzung', 'eine Anwendung'], [norsk]: ['en bruk'] },
  { [german]: ['gebrauchen', 'benutzen', 'üblicherweise tun'], [norsk]: ['bruke'] },
  { [german]: ['ein Unterschied'], [norsk]: ['en forskjell'] },
  { [german]: ['früh'], [norsk]: ['tidlig'] },
  { [german]: ['eine Limonade'], [norsk]: ['en brus'] },
  { [german]: ['trinken'], [norsk]: ['drikke'] },
  { [german]: ['oder'], [norsk]: ['eller'] },
  { [german]: ['als (bei Komparativ)', 'als'], [norsk]: ['enn'] },
  { [german]: ['bekommen', 'erhalten'], [norsk]: ['få'] },
  { [german]: ['noch immer', 'immer'], [norsk]: ['fortsatt'] },
  { [german]: ['immer'], [norsk]: ['alltid'] },
  { [german]: ['noch'], [norsk]: ['ennå'] },
  { [german]: ['noch nicht'], [norsk]: ['ikke ennå'] },
  { [german]: ['finden'], [norsk]: ['finne'] },
  { [german]: ['eine Flasche'], [norsk]: ['ei flaske'] },
  { [german]: ['für'], [norsk]: ['for'] },
  { [german]: ['ein Vorname'], [norsk]: ['et fornavn'] },
  { [german]: ['formell'], [norsk]: ['formell'] },
  { [german]: ['ziemlich', 'ganz'], [norsk]: ['ganske'] },
  { [german]: ['ein Ziegenkäse'], [norsk]: ['en geitost'] },
  { [german]: ['ein Glas'], [norsk]: ['et glass'] },
  { [german]: ['gehen'], [norsk]: ['gå'] },
  { [german]: ['tschüss'], [norsk]: ['ha det'] },
  { [german]: ['wie'], [norsk]: ['hvordan'] },
  { [german]: ['warum'], [norsk]: ['hvorfor'] },
  { [german]: ['eine Höflichkeitsform'], [norsk]: ['ei høflighetsform'] },
  { [german]: ['mit Handschlag begrüßen', 'die Hand geben'], [norsk]: ['håndhilse'] },
  { [german]: ['nicht'], [norsk]: ['ikke'] },
  { [german]: ['vorbeischauen', 'hereinschauen'], [norsk]: ['komme innom', 'stikke innom'] },
  { [german]: ['doch'], [norsk]: ['jo'] },
  { [german]: ['eine Cafeteria'], [norsk]: ['en kafeteria'] },
  { [german]: ['in einer Cafeteria'], [norsk]: ['på kafeteria'] },
  { [german]: ['ein Kaffee'], [norsk]: ['en kaffe'] },
  { [german]: ['ein Kuchen'], [norsk]: ['ei kake'] },
  { [german]: ['kaufen'], [norsk]: ['kjøpe'] },
  { [german]: ['eine Tasse'], [norsk]: ['en kopp'] },
  { [german]: ['eine Creme', 'eine Sahne'], [norsk]: ['en krem'] },
  { [german]: ['mögen'], [norsk]: ['like'] },
  { [german]: ['ein Lunch'], [norsk]: ['en lunsj'] },
  { [german]: ['ein Essen', 'eine Speise'], [norsk]: ['en mat'] },
  { [german]: ['mit'], [norsk]: ['med'] },
  { [german]: ['mich', 'mir'], [norsk]: ['meg'] },
  { [german]: ['aber'], [norsk]: ['men'] },
  { [german]: ['ein Mittagessen'], [norsk]: ['en middag'] },
  { [german]: ['zu Mittag essen'], [norsk]: ['spise middag'] },
  { [german]: ['weniger'], [norsk]: ['mindre'] },
  { [german]: ['Hallo', 'Guten Tag'], [norsk]: ['morn'] },
  { [german]: ['viel', 'viele'], [norsk]: ['mye', 'mange'] },
  { [german]: ['müssen'], [norsk]: ['måtte'] },
  { [german]: ['er muss'], [norsk]: ['han må'] },
  { [german]: ['etwas'], [norsk]: ['noe'] },
  { [german]: ['ein Norwegischlehrer'], [norsk]: ['en norsklærer'] },
  { [german]: ['oft'], [norsk]: ['ofte'] },
  { [german]: ['selten'], [norsk]: ['sjelden'] },
  { [german]: ['ein Garnelenbrot', 'ein Krabbenbrot'], [norsk]: ['et rekesmørbrød'] },
  { [german]: ['etwas kosten', 'etwas probieren'], [norsk]: ['smake på noe'] },
  { [german]: ['eine Sorte'], [norsk]: ['en sort'] },
  { [german]: ['eine Biersorte'], [norsk]: ['en ølsort'] },
  { [german]: ['sich hinsetzen', 'Platz nehmen'], [norsk]: ['sitte ned'] },
  { [german]: ['unterschiedlich'], [norsk]: ['ulik', 'forskjellig'] },
  { [german]: ['genießen'], [norsk]: ['nyte'] },
  { [german]: ['ein Brötchen'], [norsk]: ['et rundstykke'] },
  { [german]: ['später'], [norsk]: ['senere'] },
  { [german]: ['früher', 'vorher'], [norsk]: ['før'] },
  { [german]: ['sagen'], [norsk]: ['si'] },
  { [german]: ['eine Sitte'], [norsk]: ['en skikk'] },
  { [german]: ['Sitten und Bräuche'], [norsk]: ['skikk og bruk'] },
  { [german]: ['ein Schinkenbrot'], [norsk]: ['et skinkesmørbrød'] },
  { [german]: ['lieb', 'nett'], [norsk]: ['snill'] },
  { [german]: ['bitte sei so gut'], [norsk]: ['vær så snill'] },
  { [german]: ['essen'], [norsk]: ['spise'] },
  { [german]: ['hungrig'], [norsk]: ['sulten'] },
  { [german]: ['Hunger haben'], [norsk]: ['være sulten'] },
  { [german]: ['so'], [norsk]: ['så'] },
  { [german]: ['nehmen'], [norsk]: ['ta'] },
  { [german]: ['danke'], [norsk]: ['takk'] },
  { [german]: ['Zeit'], [norsk]: ['ei tid'] },
  { [german]: ['durstig'], [norsk]: ['tørst'] },
  { [german]: ['Durst haben'], [norsk]: ['være tørst'] },
  { [german]: ['Entschuldigung!'], [norsk]: ['Unnskyld!'] },
  { [german]: ['üblich', 'normal'], [norsk]: ['vanlig'] },
  { [german]: ['normalerweise'], [norsk]: ['vanligvis'] },
  { [german]: ['warm'], [norsk]: ['varm'] },
  { [german]: ['am schlechtesten'], [norsk]: ['verst'] },
  { [german]: ['nicht schlecht'], [norsk]: ['ikke så verst'] },
  { [german]: ['wissen'], [norsk]: ['vite'] },
  { [german]: ['er weiß'], [norsk]: ['han vet'] },
  { [german]: ['ein Bier'], [norsk]: ['et øl'] },
  { [german]: ['achso'], [norsk]: ['å ja'] },
  { [german]: ['guten Morgen'], [norsk]: ['god morgen'] },
  { [german]: ['guten Tag'], [norsk]: ['god dag'] },
  { [german]: ['guten Abend'], [norsk]: ['god kveld'] },
  { [german]: ['heute Abend'], [norsk]: ['i kveld'] }, 
  { [german]: ['gute Nacht'], [norsk]: ['god natt'] },
  { [german]: ['mach es gut'], [norsk]: ['ha det bra'] },

  // From here sentences to practise (Lection 2)
  { [german]: ['Das ist hier so üblich'], [norsk]: ['Det er skikk og bruk'] },
  { [german]: ['Der Unterschied zwischen A und B'], [norsk]: ['Forskjellen på A og B'] },
  { [german]: ['Han bruker å komme tidlig'], [norsk]: ['Er kommt normalerweise früh', 'Er kommt üblicherweise früh'] },
  { [german]: ['In Norwegen ist man weniger formal als in Deutschland'], [norsk]: ['I Norge er man mindre formell ein i Tyskland'] },
  { [german]: ['Frauen machen noch immer mehr Hausarbeit als Männer'], [norsk]: ['Kvinner gjør fortsatt mer husarbeid enn menn'] },
  { [german]: ['Ich weiß noch nicht'], [norsk]: ['Jeg vet ikke ennå'] },
  { [german]: ['Das ist richtig', 'Das stimmt', 'Ich stimme zu'], [norsk]: ['Det er riktig'] },
  { [german]: ['Wie geht es dir?'], [norsk]: ['Hvordan har du det?', 'Hvordan går det?'] },
  { [german]: ['In diesem Café kannst du 10 Sorten Bier probieren'], [norsk]: ['På denne kafeen kan du smake på 10 ølsorter'] },
  { [german]: ['Hier kann man sich auch hinsetzen und eine Tasse Tee genießen'], [norsk]: ['Her kan man også sitte ned og nyte en kopp te'] },
  { [german]: ['Es gibt viele unterschiedliche Sorten Tee'], [norsk]: ['Det fins mange ulike typer te'] },
  { [german]: ['Ich habe keine Zeit'], [norsk]: ['Jeg har ikke tid'] },
  { [german]: ['Danke, es geht so'], [norsk]: ['Takk, sinn passe'] },
  { [german]: ['Möchtest du nicht eine Tasse Tee habe?'], [norsk]: ['Vil du ikke ha en kopp te?'] },
  { [german]: ['Doch gerne'], [norsk]: ['Jo gjerne'] },
  { [german]: ['Ich habe keinen Durst'], [norsk]: ['Jeg er ikke tørst'] },
  { [german]: ['Ich habe keinen Hunger, ich möchte ein Bier'], [norsk]: ['Jeg er ikke sulten, jeg vil en øl'] },
  { [german]: ['Trinkt sie keinen Tee?'], [norsk]: ['Drikker hun ikke øl?'] },
  { [german]: ['Ich habe keinen Durst'], [norsk]: ['Jeg er ikke tørst'] },
  { [german]: ['Möchte sie kein Bier haben?'], [norsk]: ['Vil hun ikke ha øl?'] },
  { [german]: ['Hat Ola viel zu tun?'], [norsk]: ['Har Ola mye å gjøre?'] },
  { [german]: ['Wir müssen einen Tisch finden'], [norsk]: ['Vi må finne et bord'] },
  { [german]: ['Du musst viel arbeiten'], [norsk]: ['Du må arbeide mye'] },
  { [german]: ['Wo wollt ihr Ferien machen?'], [norsk]: ['Hvor vil der ha ferie?'] },
  { [german]: ['Woher kommen sie?'], [norsk]: ['Hvor kommer de fra?'] },
  { [german]: ['Was möchtest du essen?'], [norsk]: ['Hva vil du ha å spise?'] },
  { [german]: ['Wer ist das? Ich weiß nicht'], [norsk]: ['Hvem er det? Jeg vet ikke'] },
  { [german]: ['Uns geht es gut, aber wir haben viel zu tun'], [norsk]: ['Vi har det bra, men vi har mye å gjøre'] }
  
  // Old vocabulary
  { [german]: ['nie'], [norsk]: ['aldri'] },
  { [german]: ['dass'], [norsk]: ['at'] },
  {
    [german]: ['ein Kinderlied', 'Kinderlied'],
    [norsk]: ['en barnesang', 'barnesang'],
  },
  { [german]: ['Kinderlieder'], [norsk]: ['Barnesanger'] },
  { [german]: ['das Kinderlied'], [norsk]: ['Barnesangen'] },
  { [german]: ['die Kinderlieder'], [norsk]: ['Barnesangene'] },
  { [german]: ['ein Bild'], [norsk]: ['et bilde'] },
  { [german]: ['das Bild'], [norsk]: ['Bildet'] },
  { [german]: ['ein Buch'], [norsk]: ['ei bok'] },
  { [german]: ['das Buch'], [norsk]: ['Boka'] },
  { [german]: ['Bücher'], [norsk]: ['Bøker'] },
  { [german]: ['ein Dichter'], [norsk]: ['en dikter'] },
  { [german]: ['eigentlich'], [norsk]: ['egentlig'] },
  { [german]: ['nach'], [norsk]: ['etter'] },
  { [german]: ['ein Fall'], [norsk]: ['et fall'] },
  { [german]: ['ein Geburtstag'], [norsk]: ['en fødselsdag'] },
  { [german]: ['bevor'], [norsk]: ['før'] },
  { [german]: ['bekommen'], [norsk]: ['få'] },
  { [german]: ['ein Geschenk'], [norsk]: ['ei gave'] },
  { [german]: ['geben'], [norsk]: ['gi'] },
  { [german]: ['gratulieren'], [norsk]: ['gratulere'] },
  { [german]: ['ein Grund'], [norsk]: ['en grunn'] },
  { [german]: ['eine Laune'], [norsk]: ['et humør'] },
  { [german]: ['gemütlich'], [norsk]: ['hyggelig'] },
  { [german]: ['ein Herbst'], [norsk]: ['en høst'] },
  { [german]: ['ein Eis'], [norsk]: ['en is'] },
  { [german]: ['eine Katze'], [norsk]: ['ei katte'] },
  { [german]: ['liegen'], [norsk]: ['ligge'] },
  { [german]: ['klein'], [norsk]: ['liten'] },
  { [german]: ['ein Leben'], [norsk]: ['et liv'] },
  { [german]: ['mitten in'], [norsk]: ['midt i'] },
  { [german]: ['wenn'], [norsk]: ['når'] },
  { [german]: ['wunderschön'], [norsk]: ['nydelig'] },
  { [german]: ['scheinen'], [norsk]: ['skinne'] },
  { [german]: ['sollen'], [norsk]: ['skulen'] },
  { [german]: ['verbergen'], [norsk]: ['skjule'] },
  { [german]: ['süß'], [norsk]: ['søt'] },
  { [german]: ['eine Stunde'], [norsk]: ['en time'] },
  { [german]: ['ganz flach'], [norsk]: ['langflat'] },
  { [german]: ['ein Zeh'], [norsk]: ['ei tå'] },
  { [german]: ['zitieren'], [norsk]: ['sitere'] },
  { [german]: ['ein Text'], [norsk]: ['ei tekst'] },
  { [german]: ['der Text'], [norsk]: ['teksta'] },
  { [german]: ['die Texte'], [norsk]: ['tekstene'] },
  { [german]: ['Texte'], [norsk]: ['tekster'] },
  { [german]: ['entscheiden'], [norsk]: ['bestemme'] },
  { [german]: ['bleiben'], [norsk]: ['bli'] },
  { [german]: ['blau'], [norsk]: ['blå'] },
  { [german]: ['braun'], [norsk]: ['brun'] },
  { [german]: ['eine Hose'], [norsk]: ['ei bukse'] },
  { [german]: ['die Hose'], [norsk]: ['buksa'] },
  { [german]: ['Hosen'], [norsk]: ['bukser'] },
  { [german]: ['die Hosen'], [norsk]: ['bukserene'] },
  { [german]: ['dann'], [norsk]: ['da'] },
  { [german]: ['echt'], [norsk]: ['ekte'] },
  { [german]: ['lieben'], [norsk]: ['elske'] },
  { [german]: ['tatsächlich'], [norsk]: ['faktisk'] },
  { [german]: ['eine Farbe'], [norsk]: ['en farge'] },
  { [german]: ['voll'], [norsk]: ['full'] },
  { [german]: ['ein Pullover'], [norsk]: ['en genser'] },
  { [german]: ['grün'], [norsk]: ['grønn'] },
  { [german]: ['grå'], [norsk]: ['grau'] },
  { [german]: ['gelb'], [norsk]: ['gul'] },
  { [german]: ['anhaben'], [norsk]: ['ha på seg'] },
  { [german]: ['weiß'], [norsk]: ['hvit'] },
  { [german]: ['niemand'], [norsk]: ['ingen'] },
  { [german]: ['kalt'], [norsk]: ['kald'] },
  { [german]: ['vielleicht'], [norsk]: ['kanskje'] },
  { [german]: ['lang'], [norsk]: ['lang'] },
  { [german]: ['dunkel'], [norsk]: ['mørk'] },
  { [german]: ['die Natur'], [norsk]: ['en natur'] },
  { [german]: ['ein Name'], [norsk]: ['et navn'] },
  { [german]: ['neu'], [norsk]: ['ny'] },
  { [german]: ['versuchen'], [norsk]: ['prøve'] },
  { [german]: ['spielen'], [norsk]: ['spille'] },
  { [german]: ['ein Bart'], [norsk]: ['et skjegg'] },
  { [german]: ['ein Stein'], [norsk]: ['en stein'] },
  { [german]: ['schwarz'], [norsk]: ['svart'] },
  { [german]: ['zurück'], [norsk]: ['tilbake'] },
  { [german]: ['eine Sache'], [norsk]: ['en ting'] },
  { [german]: ['dick'], [norsk]: ['tjukk'] },
  { [german]: ['typisch'], [norsk]: ['typisk'] },
  { [german]: ['sehr'], [norsk]: ['veldig'] },
  { [german]: ['wichtig'], [norsk]: ['viktig'] },
]
