const vocables = (german, norsk) => [
  { [german]: ['nie'], [norsk]: ['aldri'] },
  { [german]: ['dass'], [norsk]: ['at'] },
  {
    [german]: ['ein Kinderlied', 'Kinderlied'],
    [norsk]: ['en barnesang', 'barnesang'],
  },
  { [german]: ['Kinderlieder'], [norsk]: ['Barnesanger'] },
  { [german]: ['das Kinderlied'], [norsk]: ['Barnesangen'] },
  { [german]: ['die Kinderlieder'], [norsk]: ['Barnesangene'] },
  { [german]: ['ein Bild'], [norsk]: ['et bilde'] },
  { [german]: ['das Bild'], [norsk]: ['Bildet'] },
  { [german]: ['ein Buch'], [norsk]: ['ei bok'] },
  { [german]: ['das Buch'], [norsk]: ['Boka'] },
  { [german]: ['Bücher'], [norsk]: ['Bøker'] },
  { [german]: ['ein Dichter'], [norsk]: ['en dikter'] },
  { [german]: ['eigentlich'], [norsk]: ['egentlig'] },
  { [german]: ['nach'], [norsk]: ['etter'] },
  { [german]: ['ein Fall'], [norsk]: ['et fall'] },
  { [german]: ['ein Geburtstag'], [norsk]: ['en fødselsdag'] },
  { [german]: ['bevor'], [norsk]: ['før'] },
  { [german]: ['bekommen'], [norsk]: ['få'] },
  { [german]: ['ein Geschenk'], [norsk]: ['ei gave'] },
  { [german]: ['geben'], [norsk]: ['gi'] },
  { [german]: ['gratulieren'], [norsk]: ['gratulere'] },
  { [german]: ['ein Grund'], [norsk]: ['en grunn'] },
  { [german]: ['eine Laune'], [norsk]: ['et humør'] },
  { [german]: ['gemütlich'], [norsk]: ['hyggelig'] },
  { [german]: ['ein Herbst'], [norsk]: ['en høst'] },
  { [german]: ['ein Eis'], [norsk]: ['en is'] },
  { [german]: ['eine Katze'], [norsk]: ['ei katte'] },
  { [german]: ['liegen'], [norsk]: ['ligge'] },
  { [german]: ['klein'], [norsk]: ['liten'] },
  { [german]: ['ein Leben'], [norsk]: ['et liv'] },
  { [german]: ['mitten in'], [norsk]: ['midt i'] },
  { [german]: ['wenn'], [norsk]: ['når'] },
  { [german]: ['wunderschön'], [norsk]: ['nydelig'] },
  { [german]: ['scheinen'], [norsk]: ['skinne'] },
  { [german]: ['sollen'], [norsk]: ['skulen'] },
  { [german]: ['verbergen'], [norsk]: ['skjule'] },
  { [german]: ['süß'], [norsk]: ['søt'] },
  { [german]: ['eine Stunde'], [norsk]: ['en time'] },
  { [german]: ['ganz flach'], [norsk]: ['langflat'] },
  { [german]: ['ein Zeh'], [norsk]: ['ei tå'] },
  { [german]: ['zitieren'], [norsk]: ['sitere'] },
  { [german]: ['ein Text'], [norsk]: ['ei tekst'] },
  { [german]: ['der Text'], [norsk]: ['teksta'] },
  { [german]: ['die Texte'], [norsk]: ['tekstene'] },
  { [german]: ['Texte'], [norsk]: ['tekster'] },
  { [german]: ['entscheiden'], [norsk]: ['bestemme'] },
  { [german]: ['bleiben'], [norsk]: ['bli'] },
  { [german]: ['blau'], [norsk]: ['blå'] },
  { [german]: ['braun'], [norsk]: ['brun'] },
  { [german]: ['eine Hose'], [norsk]: ['ei bukse'] },
  { [german]: ['die Hose'], [norsk]: ['buksa'] },
  { [german]: ['Hosen'], [norsk]: ['bukser'] },
  { [german]: ['die Hosen'], [norsk]: ['bukserene'] },
  { [german]: ['dann'], [norsk]: ['da'] },
  { [german]: ['echt'], [norsk]: ['ekte'] },
  { [german]: ['lieben'], [norsk]: ['elske'] },
  { [german]: ['tatsächlich'], [norsk]: ['faktisk'] },
  { [german]: ['eine Farbe'], [norsk]: ['en farge'] },
  { [german]: ['voll'], [norsk]: ['full'] },
  { [german]: ['ein Pullover'], [norsk]: ['en genser'] },
  { [german]: ['grün'], [norsk]: ['grønn'] },
  { [german]: ['grå'], [norsk]: ['grau'] },
  { [german]: ['gelb'], [norsk]: ['gul'] },
  { [german]: ['anhaben'], [norsk]: ['ha på seg'] },
  { [german]: ['weiß'], [norsk]: ['hvit'] },
  { [german]: ['niemand'], [norsk]: ['ingen'] },
  { [german]: ['kalt'], [norsk]: ['kald'] },
  { [german]: ['vielleicht'], [norsk]: ['kanskje'] },
  { [german]: ['lang'], [norsk]: ['lang'] },
  { [german]: ['dunkel'], [norsk]: ['mørk'] },
  { [german]: ['die Natur'], [norsk]: ['en natur'] },
  { [german]: ['ein Name'], [norsk]: ['et navn'] },
  { [german]: ['neu'], [norsk]: ['ny'] },
  { [german]: ['versuchen'], [norsk]: ['prøve'] },
  { [german]: ['spielen'], [norsk]: ['spille'] },
  { [german]: ['ein Bart'], [norsk]: ['et skjegg'] },
  { [german]: ['ein Stein'], [norsk]: ['en stein'] },
  { [german]: ['schwarz'], [norsk]: ['svart'] },
  { [german]: ['zurück'], [norsk]: ['tilbake'] },
  { [german]: ['eine Sache'], [norsk]: ['en ting'] },
  { [german]: ['dick'], [norsk]: ['tjukk'] },
  { [german]: ['typisch'], [norsk]: ['typisk'] },
  { [german]: ['sehr'], [norsk]: ['veldig'] },
  { [german]: ['wichtig'], [norsk]: ['viktig'] },
]
